# Example Properties defining an authentication module.

# Class to Module ID mappings
org.privacyidea.PrivacyIDEAModule = idp.authn.privacyIDEA

# Module Owner
idp.authn.privacyIDEA.plugin = org.privacyidea.privacyIDEA

idp.authn.privacyIDEA.name = privacyIDEA Authentication
idp.authn.privacyIDEA.desc = Login flow for the privacyIDEA
idp.authn.privacyIDEA.url = https://github.com/privacyidea/shibboleth-plugin

# Sources to add to the IdP
idp.authn.privacyIDEA.1.src = /org/privacyidea/views/main.vm
idp.authn.privacyIDEA.1.dest = views/privacyIDEA/main.vm
idp.authn.privacyIDEA.1.replace = true

idp.authn.privacyIDEA.2.src = /org/privacyidea/edit-webapp/js/pi-webauthn.js
idp.authn.privacyIDEA.2.dest = edit-webapp/js/pi-webauthn.js
idp.authn.privacyIDEA.2.replace = true

idp.authn.privacyIDEA.3.src = /org/privacyidea/doc/privacyIDEA-LICENSE.txt
idp.authn.privacyIDEA.3.dest = doc/privacyIDEA-LICENSE.txt
idp.authn.privacyIDEA.3.replace = true

idp.authn.privacyIDEA.4.src = /org/privacyidea/privacyidea.properties
idp.authn.privacyIDEA.4.dest = conf/authn/privacyidea.properties
idp.authn.privacyIDEA.4.replace = false

idp.authn.privacyIDEA.5.src = /org/privacyidea/edit-webapp/js/pi-pollTransaction.worker.js
idp.authn.privacyIDEA.5.dest = edit-webapp/js/pi-pollTransaction.worker.js
idp.authn.privacyIDEA.5.replace = true

idp.authn.privacyIDEA.6.src = /org/privacyidea/edit-webapp/js/pi-eventListeners.js
idp.authn.privacyIDEA.6.dest = edit-webapp/js/pi-eventListeners.js
idp.authn.privacyIDEA.6.replace = true

idp.authn.privacyIDEA.7.src = /org/privacyidea/edit-webapp/js/pi-utils.js
idp.authn.privacyIDEA.7.dest = edit-webapp/js/pi-utils.js
idp.authn.privacyIDEA.7.replace = true

idp.authn.privacyIDEA.8.src = /org/privacyidea/edit-webapp/js/pi-main.js
idp.authn.privacyIDEA.8.dest = edit-webapp/js/pi-main.js
idp.authn.privacyIDEA.8.replace = true

idp.authn.privacyIDEA.9.src = /org/privacyidea/edit-webapp/js/pi-pollInBrowser.js
idp.authn.privacyIDEA.9.dest = edit-webapp/js/pi-pollInBrowser.js
idp.authn.privacyIDEA.9.replace = true

idp.authn.privacyIDEA.10.src = /org/privacyidea/edit-webapp/css/pi-main.css
idp.authn.privacyIDEA.10.dest = edit-webapp/css/pi-main.css
idp.authn.privacyIDEA.10.replace = true

idp.authn.privacyIDEA.11.src = /org/privacyidea/views/usernamePasswordForm.vm
idp.authn.privacyIDEA.11.dest = views/privacyIDEA/usernamePasswordForm.vm
idp.authn.privacyIDEA.11.replace = true

idp.authn.privacyIDEA.12.src = /org/privacyidea/messages/messages.properties
idp.authn.privacyIDEA.12.dest = messages/messages.properties
idp.authn.privacyIDEA.12.replace = true

idp.authn.privacyIDEA.13.src = /org/privacyidea/privacyidea2.properties
idp.authn.privacyIDEA.13.dest = conf/authn/privacyidea2.properties
idp.authn.privacyIDEA.13.replace = false

idp.authn.privacyIDEA.14.src = /org/privacyidea/messages/messages_de.properties
idp.authn.privacyIDEA.14.dest = messages/messages_de.properties
idp.authn.privacyIDEA.14.replace = true

# Token icons (tokenSelection) and their license
idp.authn.privacyIDEA.15.src = /org/privacyidea/edit-webapp/images/privacyIDEA/4eyes.svg
idp.authn.privacyIDEA.15.dest = edit-webapp/images/privacyIDEA/4eyes.svg
idp.authn.privacyIDEA.15.replace = true

idp.authn.privacyIDEA.16.src = /org/privacyidea/edit-webapp/images/privacyIDEA/email.svg
idp.authn.privacyIDEA.16.dest = edit-webapp/images/privacyIDEA/email.svg
idp.authn.privacyIDEA.16.replace = true

idp.authn.privacyIDEA.17.src = /org/privacyidea/edit-webapp/images/privacyIDEA/hotp.svg
idp.authn.privacyIDEA.17.dest = edit-webapp/images/privacyIDEA/hotp.svg
idp.authn.privacyIDEA.17.replace = true

idp.authn.privacyIDEA.18.src = /org/privacyidea/edit-webapp/images/privacyIDEA/push.svg
idp.authn.privacyIDEA.18.dest = edit-webapp/images/privacyIDEA/push.svg
idp.authn.privacyIDEA.18.replace = true

idp.authn.privacyIDEA.19.src = /org/privacyidea/edit-webapp/images/privacyIDEA/remote.svg
idp.authn.privacyIDEA.19.dest = edit-webapp/images/privacyIDEA/remote.svg
idp.authn.privacyIDEA.19.replace = true

idp.authn.privacyIDEA.20.src = /org/privacyidea/edit-webapp/images/privacyIDEA/securitykey.svg
idp.authn.privacyIDEA.20.dest = edit-webapp/images/privacyIDEA/securitykey.svg
idp.authn.privacyIDEA.20.replace = true

idp.authn.privacyIDEA.21.src = /org/privacyidea/edit-webapp/images/privacyIDEA/shield-question.svg
idp.authn.privacyIDEA.21.dest = edit-webapp/images/privacyIDEA/shield-question.svg
idp.authn.privacyIDEA.21.replace = true

idp.authn.privacyIDEA.22.src = /org/privacyidea/edit-webapp/images/privacyIDEA/sms.svg
idp.authn.privacyIDEA.22.dest = edit-webapp/images/privacyIDEA/sms.svg
idp.authn.privacyIDEA.22.replace = true

idp.authn.privacyIDEA.23.src = /org/privacyidea/edit-webapp/images/privacyIDEA/spass.svg
idp.authn.privacyIDEA.23.dest = edit-webapp/images/privacyIDEA/spass.svg
idp.authn.privacyIDEA.23.replace = true

idp.authn.privacyIDEA.24.src = /org/privacyidea/edit-webapp/images/privacyIDEA/tan.svg
idp.authn.privacyIDEA.24.dest = edit-webapp/images/privacyIDEA/tan.svg
idp.authn.privacyIDEA.24.replace = true

idp.authn.privacyIDEA.25.src = /org/privacyidea/edit-webapp/images/privacyIDEA/totp.svg
idp.authn.privacyIDEA.25.dest = edit-webapp/images/privacyIDEA/totp.svg
idp.authn.privacyIDEA.25.replace = true

idp.authn.privacyIDEA.26.src = /org/privacyidea/edit-webapp/images/privacyIDEA/LICENSE-lucide.txt
idp.authn.privacyIDEA.26.dest = edit-webapp/images/privacyIDEA/LICENSE-lucide.txt
idp.authn.privacyIDEA.26.replace = true
